// KAG Lua script parser — regex-based, covers 80% of common patterns.
// Parses KAG.show_image, KAG.show_text, KAG.play_bgm, KAG.wait_click, KAG.clear_screen
// Returns timeline events array for visualization.

const PATTERNS = {
  showImage: /KAG\.show_image\s*\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*(?:,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+))?(?:,\s*([\d.]+))?(?:,\s*([\d.]+))?(?:,\s*(\d+))?\s*\)/g,
  showText: /KAG\.show_text\s*\(\s*"((?:[^"\\]|\\.)*)"\s*\)/g,
  playBgm: /KAG\.play_bgm\s*\(\s*"([^"]+)"\s*(?:,\s*([\d.]+))?\s*\)/g,
  stopBgm: /KAG\.stop_bgm\s*\(\s*\)/g,
  playVoice: /KAG\.play_voice\s*\(\s*"([^"]+)"\s*\)/g,
  playSe: /KAG\.play_se\s*\(\s*"([^"]+)"\s*\)/g,
  waitClick: /KAG\.wait_click\s*\(\s*\)/g,
  clearScreen: /KAG\.clear_screen\s*\(\s*(?:"([^"]*)")?\s*\)/g,
  quake: /KAG\.quake\s*\(\s*([\d.]+)\s*(?:,\s*([\d.]+))?\s*\)/g,
  transition: /KAG\.render\s*\(\s*"submit_transition"\s*(?:,\s*"([^"]*)")?\s*(?:,\s*([\d.]+))?\s*\)/g,
};

const LAYER_ORDER = { bg: 0, fg: 1, msg: 2 };
const EVENT_TYPES = {
  show_image: "image",
  show_text: "text",
  play_bgm: "audio",
  stop_bgm: "audio",
  play_voice: "audio",
  play_se: "audio",
  wait_click: "wait",
  clear_screen: "clear",
  quake: "effect",
  submit_transition: "transition",
};

export function parseKAGScript(script) {
  const events = [];
  let order = 0;

  for (const [funcName, regex] of Object.entries(PATTERNS)) {
    const re = new RegExp(regex.source, regex.flags);
    let match;
    while ((match = re.exec(script)) !== null) {
      const pos = match.index;
      const ev = {
        id: `ev_${order}`,
        type: EVENT_TYPES[funcName] || "unknown",
        func: funcName,
        position: pos,
        order: order++,
        params: {},
      };

      switch (funcName) {
        case "showImage":
          ev.params = {
            layer: match[1],
            path: match[2],
            x: match[3] ? parseFloat(match[3]) : 0,
            y: match[4] ? parseFloat(match[4]) : 0,
            scale: match[5] ? parseFloat(match[5]) : 1,
            opacity: match[6] !== undefined ? parseFloat(match[6]) : 1,
            blend: match[7] ? parseInt(match[7]) : 0,
          };
          ev.label = `🖼 ${match[1]}: ${match[2].split("/").pop()}`;
          ev.layerOrder = LAYER_ORDER[ev.params.layer] || 0;
          ev.duration = 0;
          break;
        case "showText":
          ev.params = { text: match[1] };
          ev.label = `💬 "${match[1].substring(0, 30)}${match[1].length > 30 ? "..." : ""}"`;
          ev.duration = Math.max(1500, match[1].length * 50);
          break;
        case "playBgm":
          ev.params = { path: match[1], fade: match[2] ? parseFloat(match[2]) : 1 };
          ev.label = `🎵 BGM: ${match[1].split("/").pop()}`;
          ev.duration = 0;
          break;
        case "stopBgm":
          ev.params = { fade: 1 };
          ev.label = "🎵 Stop BGM";
          ev.duration = 0;
          break;
        case "playVoice":
          ev.params = { path: match[1] };
          ev.label = `🎤 Voice: ${match[1].split("/").pop()}`;
          ev.duration = 2000;
          break;
        case "playSe":
          ev.params = { path: match[1] };
          ev.label = `🔊 SE: ${match[1].split("/").pop()}`;
          ev.duration = 500;
          break;
        case "waitClick":
          ev.params = {};
          ev.label = "⏸ Wait Click";
          ev.duration = 2000;
          break;
        case "clearScreen":
          ev.params = { layer: match[1] || "all" };
          ev.label = `🧹 Clear ${match[1] || "all"}`;
          ev.duration = 0;
          break;
        case "quake":
          ev.params = { intensity: parseFloat(match[1]), duration: match[2] ? parseFloat(match[2]) : 500 };
          ev.label = `💥 Quake x${ev.params.intensity}`;
          ev.duration = ev.params.duration;
          break;
        case "transition":
          ev.params = { type: match[1] || "fade", time: match[2] ? parseFloat(match[2]) : 0.5 };
          ev.label = `🔄 ${ev.params.type}`;
          ev.duration = ev.params.time * 1000;
          break;
      }

      events.push(ev);
    }
  }

  events.sort((a, b) => a.position - b.position);
  return events;
}

// Generate KAG Lua script from timeline events
export function generateKAGScript(events) {
  const lines = ['-- Generated by Caesura Visual Editor', '', 'function scene_start()'];
  const sorted = [...events].sort((a, b) => a.order - b.order);

  for (const ev of sorted) {
    switch (ev.func) {
      case "showImage":
        lines.push(`    KAG.show_image("${ev.params.layer}", "${ev.params.path}", ${ev.params.x}, ${ev.params.y}, ${ev.params.scale}, ${ev.params.opacity}, ${ev.params.blend})`);
        break;
      case "showText":
        lines.push(`    KAG.show_text("${ev.params.text.replace(/"/g, '\\"')}")`);
        break;
      case "playBgm":
        lines.push(`    KAG.play_bgm("${ev.params.path}", ${ev.params.fade})`);
        break;
      case "stopBgm":
        lines.push("    KAG.stop_bgm()");
        break;
      case "playVoice":
        lines.push(`    KAG.play_voice("${ev.params.path}")`);
        break;
      case "playSe":
        lines.push(`    KAG.play_se("${ev.params.path}")`);
        break;
      case "waitClick":
        lines.push("    KAG.wait_click()");
        break;
      case "clearScreen":
        lines.push(ev.params.layer === "all" ? "    KAG.clear_screen()" : `    KAG.clear_screen("${ev.params.layer}")`);
        break;
      case "quake":
        lines.push(`    KAG.quake(${ev.params.intensity}, ${ev.params.duration})`);
        break;
      case "transition":
        lines.push(`    KAG.render("submit_transition", "${ev.params.type}", ${ev.params.time})`);
        break;
    }
  }

  lines.push("end");
  lines.push("");
  lines.push("scene_start()");
  return lines.join("\n");
}

// Parse assets list from path strings found in script
export function extractAssetPaths(script) {
  const paths = new Set();
  const re = /"assets\/([^"]+)"/g;
  let m;
  while ((m = re.exec(script)) !== null) {
    paths.add("assets/" + m[1]);
  }
  return [...paths];
}