cmake_minimum_required(VERSION 3.25)

# Invoked by both the always-run build target and the CTest setup fixture.
# Only these known fixture trees are owned; output binaries and saves are not.
function(_fixture_contains parent child result)
    if(WIN32)
        string(TOLOWER "${parent}" parent)
        string(TOLOWER "${child}" child)
    endif()
    cmake_path(IS_PREFIX parent "${child}" NORMALIZE contained)
    set(${result} "${contained}" PARENT_SCOPE)
endfunction()

function(_fixture_check_existing path)
    if(IS_SYMLINK "${path}")
        message(FATAL_ERROR "Fixture sync: refusing redirected path: ${path}")
    endif()
    if(EXISTS "${path}")
        file(REAL_PATH "${path}" resolved)
        set(expected "${path}")
        if(WIN32)
            string(TOLOWER "${resolved}" resolved)
            string(TOLOWER "${expected}" expected)
        endif()
        if(NOT resolved STREQUAL expected)
            message(FATAL_ERROR "Fixture sync: refusing redirected path: ${path}")
        endif()
    endif()
endfunction()

function(_fixture_validate_path input result)
    if("${input}" MATCHES ";")
        message(FATAL_ERROR "Fixture sync: paths cannot contain list separators")
    endif()
    set(path "${input}")
    if(WIN32)
        string(REPLACE "\\" "/" path "${path}")
    endif()
    cmake_path(NORMAL_PATH path)
    cmake_path(IS_ABSOLUTE path absolute)
    if(NOT absolute)
        message(FATAL_ERROR "Fixture sync: path must be absolute: ${input}")
    endif()
    set(ancestor "${path}")
    # Inspect every existing parent, including when the output leaf is absent.
    while(TRUE)
        _fixture_check_existing("${ancestor}")
        if(EXISTS "${ancestor}" AND NOT IS_DIRECTORY "${ancestor}")
            message(FATAL_ERROR "Fixture sync: expected directory: ${ancestor}")
        endif()
        cmake_path(GET ancestor PARENT_PATH parent)
        if(parent STREQUAL ancestor)
            break()
        endif()
        set(ancestor "${parent}")
    endwhile()
    set(${result} "${path}" PARENT_SCOPE)
endfunction()

function(_fixture_validate_tree path)
    # Validate each directory before descending, so junctions are never traversed.
    # The directory prefix is literal; only the final /* is a glob expression.
    string(REGEX REPLACE "([][?*])" "[\\1]" glob_prefix "${path}")
    file(GLOB children LIST_DIRECTORIES TRUE "${glob_prefix}/*")
    foreach(child IN LISTS children)
        # GLOB returns a CMake list. A ';' in a filename splits it into fragments,
        # including an empty suffix, which must never bypass redirect validation.
        if(NOT IS_ABSOLUTE "${child}" OR (NOT EXISTS "${child}" AND NOT IS_SYMLINK "${child}"))
            message(FATAL_ERROR "Fixture sync: ambiguous directory entry beneath: ${path}")
        endif()
        _fixture_check_existing("${child}")
        if(IS_DIRECTORY "${child}")
            _fixture_validate_tree("${child}")
        endif()
    endforeach()
endfunction()

foreach(name SOURCE_ROOT BUILD_ROOT TEST_OUTPUT APP_OUTPUT)
    if(NOT DEFINED CAESURA_FIXTURE_${name})
        message(FATAL_ERROR "Fixture sync: missing CAESURA_FIXTURE_${name}")
    endif()
    _fixture_validate_path("${CAESURA_FIXTURE_${name}}" ${name})
endforeach()
foreach(root SOURCE_ROOT BUILD_ROOT)
    if(NOT IS_DIRECTORY "${${root}}")
        message(FATAL_ERROR "Fixture sync: missing directory: ${${root}}")
    endif()
endforeach()
cmake_path(GET BUILD_ROOT ROOT_PATH filesystem_root)
if(BUILD_ROOT STREQUAL filesystem_root)
    message(FATAL_ERROR "Fixture sync: build root cannot be a filesystem root")
endif()
_fixture_contains("${BUILD_ROOT}" "${SOURCE_ROOT}" contains_source)
if(contains_source)
    message(FATAL_ERROR "Fixture sync: build root cannot be source root or its ancestor")
endif()
foreach(output "${TEST_OUTPUT}" "${APP_OUTPUT}")
    _fixture_contains("${BUILD_ROOT}" "${output}" inside_build)
    if(NOT inside_build)
        message(FATAL_ERROR "Fixture sync: output is outside build root: ${output}")
    endif()
endforeach()

set(fixtures scripts assets demo tests/audio)
set(sources)
set(destinations)
foreach(relative IN LISTS fixtures)
    set(source "${SOURCE_ROOT}/${relative}")
    _fixture_validate_path("${source}" source)
    if(NOT IS_DIRECTORY "${source}")
        message(FATAL_ERROR "Fixture sync: missing source fixture: ${source}")
    endif()
    _fixture_contains("${source}" "${BUILD_ROOT}" build_in_fixture)
    if(build_in_fixture)
        message(FATAL_ERROR "Fixture sync: build root overlaps source fixture: ${source}")
    endif()
    _fixture_validate_tree("${source}")
    list(APPEND sources "${source}")
    list(APPEND destinations "${TEST_OUTPUT}/${relative}")
    if(NOT relative STREQUAL "tests/audio")
        list(APPEND sources "${source}")
        list(APPEND destinations "${APP_OUTPUT}/${relative}")
    endif()
endforeach()

# Preflight ALL destinations before deleting even the first owned fixture tree.
foreach(destination IN LISTS destinations)
    _fixture_validate_path("${destination}" validated)
    _fixture_contains("${BUILD_ROOT}" "${validated}" inside_build)
    if(NOT inside_build OR validated STREQUAL BUILD_ROOT)
        message(FATAL_ERROR "Fixture sync: destination is outside build root: ${validated}")
    endif()
    foreach(source IN LISTS sources)
        _fixture_contains("${source}" "${validated}" inside_source)
        _fixture_contains("${validated}" "${source}" contains_source)
        if(inside_source OR contains_source)
            message(FATAL_ERROR "Fixture sync: destination overlaps source fixture: ${validated}")
        endif()
    endforeach()
    foreach(other IN LISTS destinations)
        _fixture_contains("${validated}" "${other}" contains_other)
        _fixture_contains("${other}" "${validated}" contained_by_other)
        if(contains_other AND NOT contained_by_other)
            message(FATAL_ERROR "Fixture sync: overlapping destination trees: ${validated} and ${other}")
        endif()
    endforeach()
    _fixture_validate_tree("${validated}")
endforeach()

list(LENGTH sources count)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    list(GET sources ${index} source)
    list(GET destinations ${index} destination)
    file(REMOVE_RECURSE "${destination}")
    if(EXISTS "${destination}" OR IS_SYMLINK "${destination}")
        message(FATAL_ERROR "Fixture sync: cannot remove owned fixture tree: ${destination}")
    endif()
    file(MAKE_DIRECTORY "${destination}")
    file(COPY "${source}/" DESTINATION "${destination}")
endforeach()
