-- Auto-generated by scripts/ks_i18n.lua (do not edit by hand)
-- Scene: demo | keys: 23
return {
  fullscreen = "フルスクリーン",
  skip_mode = "スキップ",
  save = "セーブ",
  thank_you = "ありがとう！",
  cancel = "キャンセル",
  greeting = "こんにちは！",
  prev_page = "前へ",
  volume_bgm = "BGM音量",
  next_page = "次へ",
  no = "いいえ",
  volume_voice = "ボイス音量",
  farewell = "さようなら！",
  load_game = "ロード",
  confirm = "決定",
  new_game = "ニューゲーム",
  auto_mode = "オート",
  continue = "コンティニュー",
  language = "言語",
  yes = "はい",
  text_speed = "文字速度",
  title_screen = "タイトル",
  volume_se = "SE音量",
  back = "戻る",
  gallery = "CG鑑賞",
  close = "閉じる",
  music_room = "音楽室",
  load = "ロード",
  settings = "設定",
  lines = {
    -- full_pipeline_demo.ks
    ["full_pipeline_demo.ks:724a1028"] = "", -- original: Welcome to the Caesura full-pipeline demo.
    ["full_pipeline_demo.ks:64e415a8"] = "", -- original: 现在是中文与日文渲染测试。
    ["full_pipeline_demo.ks:f6b38aac"] = "", -- original: Ruby annotation:
    ["full_pipeline_demo.ks:181cb20e"] = "", -- original: Hello! Nice to meet you.
    ["full_pipeline_demo.ks:4120089b"] = "", -- original: The condition evaluated to true.
    ["full_pipeline_demo.ks:f3ee959c"] = "", -- original: The condition evaluated to false.
    ["full_pipeline_demo.ks:22937793"] = "", -- original: Eval and iscript executed.
    ["full_pipeline_demo.ks:86e73762"] = "", -- original: Which route will you take?
    ["full_pipeline_demo.ks:7ec48409"] = "", -- original: You chose the library route.
    ["full_pipeline_demo.ks:eeb193ad"] = "", -- original: Progress saved to slot 1.
    ["full_pipeline_demo.ks:1e571d7e"] = "", -- original: The full-pipeline demo has completed.
    ["full_pipeline_demo.ks:196b8611"] = "", -- original: Thank you for playing.
    -- galgame_demo.ks
    ["galgame_demo.ks:21c6c4b9"] = "", -- original: Welcome to Caesura AmeKAG Engine Demo.
    ["galgame_demo.ks:d77b7aab"] = "", -- original: This is a test of the KAG scripting system.
    ["galgame_demo.ks:cd0c6cb8"] = "", -- original: Afternoon sunlight filters through the window.
    ["galgame_demo.ks:1a4d3e0f"] = "", -- original: Welcome to our class. Today we learn something interesting.
    ["galgame_demo.ks:c98748ab"] = "", -- original: After class, you walk to the hallway.
    ["galgame_demo.ks:0d0b7e40"] = "", -- original: Hello! Are you a new student? My name is Sakura.
    ["galgame_demo.ks:05ab2df1"] = "", -- original: (she leans in, a little shy)
    ["galgame_demo.ks:f3108676"] = "", -- original: After school, you go to the library with Sakura.
    ["galgame_demo.ks:2453b987"] = "", -- original: Look, there is an old notebook here.
    ["galgame_demo.ks:4d37f09a"] = "", -- original: The day ends. You return home, looking forward to tomorrow.
    ["galgame_demo.ks:154f152a"] = "", -- original: Thank you for watching the Caesura AmeKAG demo.
  },
}
