#!/bin/bash
# Metal shader embedding for bgfx (source code, compiled at runtime by newLibraryWithSource)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
METAL_DIR="$SCRIPT_DIR/metal"
CPP_OUT="$SCRIPT_DIR/../src/Render/EmbeddedShaders_Metal.cpp"

echo "=== Embedding Metal shader source ==="
cat > "$CPP_OUT" << 'HEAD'
// Auto-generated by shaders/embed_metal.sh — Metal Shading Language source for bgfx
#include "EmbeddedShaders.h"
// (namespace opened by parent EmbeddedShaders.cpp)
HEAD

for f in "$METAL_DIR"/*.metal; do
    name=$(basename "$f" .metal)
    c_name="kEmbeddedMetal_$(echo "$name" | sed 's/\./_/g' | sed 's/-/_/g' \
        | sed 's/^vs_sprite$/VS_Sprite/' | sed 's/^fs_texture$/FS_Texture/')"
    echo "  $name.metal -> $c_name"
    python3 -c "
data = open('$f', 'rb').read()
import sys
sys.stdout.write('extern const uint8_t ${c_name}[] = {')
for i, b in enumerate(data):
    if i % 12 == 0: sys.stdout.write('\n    ')
    sys.stdout.write(f'0x{b:02x}, ')
sys.stdout.write('\n};\n')
sys.stdout.write(f'extern const size_t ${c_name}_size = {len(data)};\n')
" >> "$CPP_OUT"
    echo "" >> "$CPP_OUT"
done
echo "// (namespace closed by parent EmbeddedShaders.cpp)" >> "$CPP_OUT"
echo "Done: $CPP_OUT"
