[set var="f.before" value=1]
[save slot=38 thumbnail="u11-inline"]
[set var="f.replayed" value=1]
[ch name="N" text="RESTORED-MARKER"]
[if exp="tf.load_result == 'ok'"]
[set var="f.branch" value="restored"]
[else]
[set var="f.future_only" value=true]
[load slot=38]
[endif]
[set var="f.finished" value=true]
[wait time=60000]
[end]
