#!/usr/bin/env python3
"""Mutation regression for execution provenance, independent of local release bundles.

Fixtures are explicitly synthetic and confined to TemporaryDirectory. A valid
fixture may pass diagnostic validation, but can NEVER pass release verification.
No repository artifacts, reports or source history are read or rewritten.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

from test_validation_evidence import EvidenceFixture, sha
from collect_validation_evidence import EvidenceError
import compare_platform_parity as comparator
from verify_release_candidate import verify_evidence


class TestReleaseCandidateAdversarialMutations(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="caesura-rc-mutation-")
        self.addCleanup(temporary.cleanup)
        self.f = EvidenceFixture(Path(temporary.name))

    def test_baseline_fixture_diagnostic_validation(self):
        self.f.collect()
        self.assertEqual(self.f.verify(), [])

    def test_fixture_never_grants_release(self):
        self.f.collect()
        self.assertTrue(self.f.verify(release=True))

    def test_missing_manifest_rejected(self):
        self.f.collect()
        (self.f.output / "manifest.json").unlink()
        self.assertTrue(self.f.verify())

    def test_invalid_manifest_json_rejected(self):
        self.f.collect()
        (self.f.output / "manifest.json").write_text("{truncated", encoding="utf-8")
        self.assertTrue(self.f.verify())

    def test_legacy_autogenerated_rc_go_not_execution_evidence(self):
        self.f.collect()
        (self.f.output / "manifest.json").write_text(
            json.dumps({"decision": "RC-GO", "commit": "a" * 40}), encoding="utf-8")
        self.assertTrue(any("Legacy" in error for error in self.f.verify()))

    def test_bundled_receipt_cannot_be_its_own_trust_anchor(self):
        self.f.collect()
        errors = verify_evidence(self.f.output, self.f.profile_path, "test-debug",
                                 self.f.output / "execution-receipt.json", source_sha="a" * 40, release=False)
        self.assertTrue(errors)

    def test_bundled_profile_cannot_be_its_own_trust_anchor(self):
        self.f.collect()
        errors = verify_evidence(self.f.output, self.f.output / "profile.json", "test-debug",
                                 self.f.run_path, source_sha="a" * 40, release=False)
        self.assertTrue(errors)

    def test_trusted_profile_cannot_be_reduced_after_execution(self):
        self.f.collect()
        self.f.profile["profiles"]["test-debug"]["checks"][0]["required"] = False
        self.f.write_profile()
        self.assertTrue(self.f.verify())

    def test_receipt_cannot_select_different_profile_name(self):
        self.f.run["profile_name"] = "another-profile"
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_source_change_during_execution_not_pass(self):
        self.f.run["source_changed_during_run"] = True
        self.f.run["finished_worktree_fingerprint"] = "d" * 64
        self.assertEqual(self.f.collect()["result"], "FAIL")

    def test_changed_fingerprint_without_changed_flag_rejected(self):
        self.f.run["source_changed_during_run"] = False
        self.f.run["finished_worktree_fingerprint"] = "d" * 64
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_fixture_change_during_execution_is_failure(self):
        self.f.run["fixtures_changed_during_run"] = True
        self.f.run["finished_fixture_sha256"] = "d" * 64
        self.assertEqual(self.f.collect()["result"], "FAIL")
        self.assertTrue(any("Fixture" in error for error in self.f.verify()))

    def test_changed_fixture_without_changed_flag_rejected(self):
        self.f.run["finished_fixture_sha256"] = "d" * 64
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_missing_finished_fixture_identity_is_rejected(self):
        del self.f.run["finished_fixture_sha256"]
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_null_finished_fixture_requires_computation_error_and_change_flag(self):
        self.f.run["finished_fixture_sha256"] = None
        self.f.run["fixtures_changed_during_run"] = True
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_fixture_fingerprint_computation_error_remains_failure(self):
        self.f.run.update(finished_fixture_sha256=None, fixtures_changed_during_run=True,
                          fixture_error="fixture disappeared during execution")
        self.assertEqual(self.f.collect()["result"], "FAIL")
        self.assertTrue(self.f.verify())

    def test_collected_report_symlink_cannot_escape_bundle(self):
        self.f.collect()
        bundled = self.f.output / "inputs/cpp/stdout"
        outside = self.f.raw / "cpp.stdout"
        original_resolve = Path.resolve

        def symlink_resolution(path, *args, **kwargs):
            return outside if path == bundled else original_resolve(path, *args, **kwargs)

        # Model filesystem symlink resolution without requiring Windows symlink privileges.
        with patch.object(Path, "resolve", symlink_resolution):
            self.assertTrue(self.f.verify())

    def test_check_time_cannot_extend_beyond_run(self):
        self.f.run["checks"][0]["finished_at"] = "2027-01-01T00:00:00Z"
        with self.assertRaises(EvidenceError):
            self.f.collect()

    def test_exit_77_is_skip_and_fails_required_gate(self):
        self.f.run["checks"][0]["exit_code"] = 77
        manifest = self.f.collect()
        self.assertEqual(manifest["checks"][0]["result"], "SKIP")
        self.assertEqual(manifest["result"], "FAIL")
        self.assertTrue(self.f.verify())

    def test_ctest_named_optional_skip_stays_visible(self):
        self.f.profile["profiles"]["test-debug"]["checks"][0].update(
            parser="ctest-junit", allowed_skips=["optional-ai"])
        self.f.write_profile()
        self.f.run["profile_sha256"] = sha(self.f.profile_path)
        self.f.run["checks"][0]["report"] = self.f.file("ctest.xml",
            '<testsuite tests="2"><testcase name="core"/><testcase name="optional-ai"><skipped/></testcase></testsuite>')
        manifest = self.f.collect()
        self.assertEqual(manifest["result"], "PASS")
        self.assertEqual(manifest["checks"][0]["counts"]["skipped"], 1)

    def test_unlisted_ctest_skip_is_failure(self):
        self.f.profile["profiles"]["test-debug"]["checks"][0]["parser"] = "ctest-junit"
        self.f.write_profile()
        self.f.run["profile_sha256"] = sha(self.f.profile_path)
        self.f.run["checks"][0]["report"] = self.f.file("ctest.xml",
            '<testsuite tests="2"><testcase name="core"/><testcase name="required-save"><skipped/></testcase></testsuite>')
        self.assertEqual(self.f.collect()["result"], "FAIL")


def manifest_mutation(path, value):
    def test(self):
        manifest = self.f.collect()
        target = manifest
        for key in path[:-1]:
            target = target[key]
        target[path[-1]] = copy.deepcopy(value)
        (self.f.output / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
        self.assertTrue(self.f.verify(), f"Mutation not rejected: {path}")
    return test


for name, path, value in [
    ("source_sha", ("context", "source_sha"), "d" * 40),
    ("workflow", ("context", "workflow"), "other-workflow"),
    ("repository", ("context", "repository"), "attacker/repo"),
    ("run_attempt", ("context", "run_attempt"), 2),
    ("run_id", ("context", "run_id"), "other-run"),
    ("fixture_digest", ("context", "fixture_sha256"), "d" * 64),
    ("finished_fixture_digest", ("context", "finished_fixture_sha256"), "d" * 64),
    ("fixture_change_flag", ("context", "fixtures_changed_during_run"), True),
    ("worktree_fingerprint", ("context", "worktree_fingerprint"), "d" * 64),
    ("purpose", ("context", "purpose"), "validation"),
    ("toolchain", ("context", "toolchain"), {}),
    ("timestamp", ("context", "finished_at"), "2025-01-01T00:00:00Z"),
    ("result", ("result",), "RC-GO"),
    ("profile_name", ("profile_name",), "other"),
    ("profile_digest", ("profile_sha256",), "d" * 64),
    ("receipt_digest", ("receipt_sha256",), "d" * 64),
    ("discovery_count", ("checks", 0, "counts", "discovered"), 1),
    ("passed_count", ("checks", 0, "counts", "passed"), 10000),
    ("failed_count", ("checks", 0, "counts", "failed"), 1),
    ("skipped_count", ("checks", 0, "counts", "skipped"), 1),
    ("executed_count", ("checks", 0, "counts", "executed"), 0),
    ("required_flag", ("checks", 0, "required"), False),
    ("check_parser", ("checks", 0, "parser"), "exit-code"),
    ("exit_code", ("checks", 0, "exit_code"), 77),
    ("command", ("checks", 0, "command"), ["echo", "PASS"]),
    ("cwd", ("checks", 0, "cwd"), "other-directory"),
    ("binary_digest", ("checks", 0, "files", "binary", "sha256"), "d" * 64),
    ("executed_program_digest", ("checks", 0, "files", "executed_program", "sha256"), "d" * 64),
    ("log_path_traversal", ("checks", 0, "files", "stdout", "path"), "../../outside"),
    ("log_digest", ("checks", 0, "files", "stdout", "sha256"), "d" * 64),
    ("checks_removed", ("checks",), []),
]:
    setattr(TestReleaseCandidateAdversarialMutations, f"test_mutation_{name}", manifest_mutation(path, value))


class ParityMutationTests(unittest.TestCase):
    """Keep comparator adversarial coverage using clearly local constructed data."""

    def test_gpu_key_is_not_semantic_parity(self):
        self.assertTrue(comparator.sanitize_check_obj({"route_a": {"gpu_vendor": "fixture"}}))

    def test_native_pointer_is_not_semantic_parity(self):
        self.assertTrue(comparator.sanitize_check_obj({"route_a": {"handle": "0x7ffe00112233"}}))

    def test_absolute_path_is_not_semantic_parity(self):
        self.assertTrue(comparator.sanitize_check_obj({"route_a": {"save_path": "/home/fixture/save"}}))

    def test_missing_locale_rejected(self):
        route = {**comparator.CANONICAL_ROUTE_A, "languages": ["zh", "en"]}
        self.assertTrue(comparator.compare_route(route, comparator.CANONICAL_ROUTE_A, "route_a"))

    def test_divergent_ending_rejected(self):
        route = {**comparator.CANONICAL_ROUTE_B, "ending": "different"}
        self.assertTrue(comparator.compare_route(route, comparator.CANONICAL_ROUTE_B, "route_b"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
